//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstrellaWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись
    {
        public int Id { get; set; }
        public System.DateTime Дата { get; set; }
        public System.TimeSpan Время { get; set; }
        public int id_услуги { get; set; }
        public int id_клиента { get; set; }
        public int id_сотрудника { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
