//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstrellaWebApi.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int Id { get; set; }
        public string День_недели { get; set; }
        public int id_сотрудника { get; set; }
        public int id_тип_дня { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ТипДня ТипДня { get; set; }
    }
}
